### ISSUE TITLE
Alot of errors?

### ISSUE THREAD

**Issue by Ackzel** [OregonCore/OregonCore#1366]
Alot of errors are showing up after running all of the sql updates from the updates folder, here's the print.

`2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (11980) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (11980) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (11980) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (11980) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (16544) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (16544) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (16544) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (16544) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (16544) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (16544) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (16545) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (16545) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (16545) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (16545) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18069) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18398) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18398) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18398) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18399) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18399) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18399) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18399) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18399) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18399) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18400) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18400) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18400) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18400) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18400) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18400) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18400) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18401) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18401) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18401) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18401) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18401) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18402) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18402) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18402) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18402) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18402) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18402) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18402) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (18471) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19409) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19409) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19409) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (19720) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20058) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20763) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20763) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20763) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20763) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20763) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20763) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20763) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20763) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20763) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20763) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20763) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (20763) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (21183) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (21183) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (21503) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (21506) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (21506) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (22293) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (23415) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr::LoadSmartAIFromDB: Creature entry (23415) is not using SmartAI, skipped loading.
2016-04-27 23:34:34 SmartAIMgr: Entry 1806901 SourceType 9 Event 3 Action 49 has maxDist 0 as target_param1, skipped.`

and `2016-04-27 23:34:34 OSCR: Missing version.script_version information.`

Also, everytime I create a character ingame it wont show up, instead the console says something about Modelspawn file name too long.

I would really appreciate any help since I just want to start bugg fixing asap.

**Comment by dikkedeur** [comment]
seems to me you have alot of smartai entries in smart_scripts that are not assigned in the creature_template.

example the first error creature: 11980
in my oregondb its not in smart_scripts table, but in creature_template ID 11980 is a script assgined called: npc_zuluhed_the_whacked

so i think you have some wrong smart_scripts in your database..

my suggestion,
Drop database, insert from repo the oregon_full database ( its a zip file so unpack it first )
then in config set database update to 1 and set correct path

to quote @Zaffy from the forum

If you want full database, drop world db, run world.sql then oregon_database.zip, turn autoupdater on and run core. That will make you latest db.

**Comment by Ackzel** [comment]
Where would I find the autoupdater?

/// nevermind found.

**Comment by Ackzel** [comment]
Okay, I'am still getting "Error reading ModelSpawn, file name too long" when I create a character, what's that

**Comment by Ackzel** [comment]
I also get some errors saying my map folders are incompatible, however i just extracted them 5 minutes ago?
Is there some place I can download compadible versions?

**Comment by LordUsagi** [comment]
Sounds like incorrect dbc, map stuff. You extracted them 5 minutes ago with your own compiled extractors?

**Comment by Ackzel** [comment]
Yes

**Comment by Ackzel** [comment]
Rebuilt everything and tried again, but now I cant run the mmap_extract python script, it returns "print "++ %s" % (name)"   Syntax errors?

**Comment by Ackzel** [comment]
This is my current error, outputted from mmap_extract.py 

`Exception in thread Thread-60:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in **bootstrap_inner
    self.run()
  File "D:\World of Warcraft 2.4.3\mmap_extract.py", line 45, in run
    retcode = subprocess.call([binName, "%u" % (self.mapID),"--silent"], startup
info=stInfo, creationflags=cFlags)
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init**
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [winerror 2] the system cannot find the file specified

Fixed the print errors by putting the line inside brackets.

**Comment by Ackzel** [comment]
Fixed all the errors but the script will not fill the mmaps directory with files? 

`I will always maintain 4 MoveMapGen tasks running in //

++ Worker for map 0
++ Worker for map 1
++ Worker for map 13
++ Worker for map 25
-- Worker for map 0
++ Worker for map 29
-- Worker for map 1
++ Worker for map 30
-- Worker for map 13
++ Worker for map 33
-- Worker for map 25
++ Worker for map 34
-- Worker for map 29
++ Worker for map 35
-- Worker for map 30
++ Worker for map 36
-- Worker for map 33
++ Worker for map 37
-- Worker for map 34
++ Worker for map 42
-- Worker for map 35
++ Worker for map 43
-- Worker for map 36
++ Worker for map 44
-- Worker for map 37
++ Worker for map 47
-- Worker for map 42
++ Worker for map 48
-- Worker for map 43
++ Worker for map 70
-- Worker for map 44
-- Worker for map 47
++ Worker for map 90
++ Worker for map 109
-- Worker for map 48
++ Worker for map 129
-- Worker for map 70
++ Worker for map 169
-- Worker for map 90
++ Worker for map 189
-- Worker for map 109
++ Worker for map 209
-- Worker for map 129
++ Worker for map 229
-- Worker for map 169
++ Worker for map 230
-- Worker for map 189
++ Worker for map 249
-- Worker for map 209
++ Worker for map 269
-- Worker for map 229
++ Worker for map 289
-- Worker for map 230
++ Worker for map 309
-- Worker for map 249
++ Worker for map 329
-- Worker for map 269
++ Worker for map 349
-- Worker for map 289
++ Worker for map 369
-- Worker for map 309
++ Worker for map 389
-- Worker for map 329
++ Worker for map 409
-- Worker for map 349
++ Worker for map 429
-- Worker for map 369
++ Worker for map 449
-- Worker for map 389
++ Worker for map 450
-- Worker for map 409
++ Worker for map 451
-- Worker for map 429
++ Worker for map 469
-- Worker for map 449
++ Worker for map 489
-- Worker for map 450
++ Worker for map 509
-- Worker for map 451
++ Worker for map 529
-- Worker for map 469
-- Worker for map 489
++ Worker for map 530
++ Worker for map 531
-- Worker for map 509
++ Worker for map 532
-- Worker for map 529
++ Worker for map 533
-- Worker for map 530
++ Worker for map 534
-- Worker for map 531
++ Worker for map 540
-- Worker for map 532
++ Worker for map 542
-- Worker for map 533
++ Worker for map 543
-- Worker for map 534
++ Worker for map 544
-- Worker for map 540
++ Worker for map 545
-- Worker for map 542
++ Worker for map 546
-- Worker for map 543
++ Worker for map 547
-- Worker for map 544
++ Worker for map 548
-- Worker for map 545
++ Worker for map 550
-- Worker for map 546
++ Worker for map 552
-- Worker for map 547
++ Worker for map 553
-- Worker for map 548
-- Worker for map 550
++ Worker for map 554
++ Worker for map 555
-- Worker for map 552
++ Worker for map 556
-- Worker for map 553
++ Worker for map 557
-- Worker for map 554
++ Worker for map 558
-- Worker for map 555
++ Worker for map 559
-- Worker for map 556
++ Worker for map 560
-- Worker for map 557
++ Worker for map 562
-- Worker for map 558
++ Worker for map 564
-- Worker for map 559
++ Worker for map 565
-- Worker for map 560
++ Worker for map 566
-- Worker for map 562
++ Worker for map 568
-- Worker for map 564
-- Worker for map 565
++ Worker for map 572
++ Worker for map 580
-- Worker for map 566
++ Worker for map 582
-- Worker for map 568
++ Worker for map 584
-- Worker for map 572
++ Worker for map 585
-- Worker for map 580
++ Worker for map 586
-- Worker for map 582
++ Worker for map 587
-- Worker for map 584
++ Worker for map 588
-- Worker for map 585
++ Worker for map 589
-- Worker for map 586
++ Worker for map 590
-- Worker for map 587
++ Worker for map 591
-- Worker for map 588
++ Worker for map 593
-- Worker for map 589
++ Worker for map 598
-- Worker for map 590
-- Worker for map 591
-- Worker for map 593
-- Worker for map 598`

Looks like it is removing or something?

**Comment by LordUsagi** [comment]
I've never used the python script so I won't be able to assist. Have you tried running them manually?

**Comment by Ackzel** [comment]
I'am currently running the map extractor manually and it seems to be working.

**Comment by Ackzel** [comment]
Python script does not seem to work and anyone trying to use it should do it manually with map_extractor.exe, it only took me around 2-3 hours on windows.
