### ISSUE TITLE
std::_Rb_tree_increment Segmentation fault

### ISSUE THREAD

**Issue by lyrl** [OregonCore/OregonCore#1507]
**Revision**:
latest
**Operating system**:
ubuntu 14.04 64bit
**Current behavior**: 
....

```
#0  0x00007f0228cdab13 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#1  0x0000000000c20b9f in std::_Rb_tree_iterator<std::pair<unsigned int const, QuestStatusData> >::operator++ (this=0x7fff870845e0) at /usr/include/c++/4.8/bits/stl_tree.h:189
No locals.
#2  0x0000000000dc5eaa in Player::HasQuestForGO (this=0x7f017fc61000, GOId=3706)
    at /root/OregonCorel/src/game/Player.cpp:19443
        i = {first = 651, second = {m_status = QUEST_STATUS_INCOMPLETE, m_rewarded = false, 
            m_explored = false, m_timer = 0, uState = QUEST_UNCHANGED, m_itemcount = {1, 0, 
              0, 0}, m_creatureOrGOcount = {0, 0, 0, 0}}}
#3  0x0000000000cb80e5 in GameObject::ActivateToQuest (this=0x7f019c652000, 
    pTarget=0x7f017fc61000) at /root/OregonCorel/src/game/GameObject.cpp:849
No locals.
#4  0x0000000000bd1b11 in Object::_BuildValuesUpdate (this=0x7f019c652000, 
    updatetype=0 '\000', data=0x7fff87084740, updateMask=0x7fff87084730, 
    target=0x7f017fc61000) at /root/OregonCorel/src/game/Object.cpp:473
        IsActivateToQuest = false
        __FUNCTION__ = "_BuildValuesUpdate"
        __PRETTY_FUNCTION__ = "void Object::_BuildValuesUpdate(uint8, ByteBuffer*, UpdateMask*, Player*) const"
#5  0x0000000000bd0f88 in Object::BuildValuesUpdateBlockForPlayer (this=0x7f019c652000, 
    data=0x7fff870847f0, target=0x7f017fc61000) at /root/OregonCorel/src/game/Object.cpp:231
        buf = {static DEFAULT_SIZE = 4096, _rpos = 0, _wpos = 10, 
          _storage = std::vector of length 10, capacity 500 = {0 '\000', 255 '\377', 
            14 '\016', 66 'B', 0 '\000', 122 'z', 14 '\016', 0 '\000', 16 '\020', 241 '\361'}}
        updateMask = {mCount = 26, mBlocks = 1, mUpdateMask = 0x7f021361a520}
#6  0x0000000000dc5fbc in Player::UpdateForQuestsGO (this=0x7f017fc61000)
    at /root/OregonCorel/src/game/Player.cpp:19480
        obj = 0x7f019c652000
        itr = 17370383824944382478
---Type <return> to continue, or q <return> to quit---
        udata = {m_blockCount = 0, m_outOfRangeGUIDs = std::set with 0 elements, m_data = {
            static DEFAULT_SIZE = 4096, _rpos = 0, _wpos = 0, 
            _storage = std::vector of length 0, capacity 4096}}
        packet = {<ByteBuffer> = {static DEFAULT_SIZE = 4096, _rpos = 0, _wpos = 0, 
            _storage = std::vector of length 0, capacity 0}, m_opcode = 0}
#7  0x0000000000daf8d4 in Player::ItemAddedQuestCheck (this=0x7f017fc61000, entry=16883, 
    count=1) at /root/OregonCorel/src/game/Player.cpp:13775
No locals.
#8  0x0000000000da38d4 in Player::StoreNewItem (this=0x7f017fc61000, 
    dest=std::vector of length 1, capacity 1 = {...}, item=16883, update=true, 
    randomPropertyId=0) at /root/OregonCorel/src/game/Player.cpp:10263
        count = 1
        pItem = 0x7f01755ac200
#9  0x0000000000f1f1f6 in WorldSession::HandleAutostoreLootItemOpcode (this=0x7f01ba1a6880, 
    recv_data=...) at /root/OregonCorel/src/game/LootHandler.cpp:115
        newitem = 0xae2599 <ACE_Guard<ACE_Thread_Mutex>::release()+57>
        player = 0x7f017fc61000
        ffaitem = 0x0
        conditem = 0x0
        loot = 0x7f019c993cb0
        qitem = 0x0
        item = 0x7f01694cb480
        msg = 0 '\000'
        lguid = 17379391005123426562
        lootSlot = 0 '\000'
        dest = std::vector of length 1, capacity 1 = {{pos = 5126, count = 1 '\001'}}
#10 0x0000000000ee19b6 in WorldSession::ExecuteOpcode (this=0x7f01ba1a6880, opHandle=..., 
    packet=0x7f017483e300) at /root/OregonCorel/src/game/WorldSession.cpp:609
```

**Comment by AbraKabastard** [comment]
Quite a big time period. Potentially solved.
